version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: usermongoDB
    ports:
      - "27017:27017"

  userrestapi:
    image: com.fishmarket/userrestapi
    ports:
      - "8081:8081"
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/usermongodb